// generated by image optimization script
export type ResponsiveImageVariant = { src: string; width: number; height: number };
export type ResponsiveImage = { width: number; height: number; variants: ResponsiveImageVariant[] };
export const responsiveImages = {
  "/images/Haus/gaestehaus-sommer.jpg": {
    "width": 2048,
    "height": 1152,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Haus/gaestehaus-sommer-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Haus/gaestehaus-sommer-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Haus/gaestehaus-sommer-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Haus/gaestehaus-sommer-1600.webp"
      }
    ]
  },
  "/images/Haus/balkon-ausblick-winter.jpg": {
    "width": 2048,
    "height": 1152,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Haus/balkon-ausblick-winter-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Haus/balkon-ausblick-winter-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Haus/balkon-ausblick-winter-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Haus/balkon-ausblick-winter-1600.webp"
      }
    ]
  },
  "/images/Haus/gaestehaus-balkon-ausblick.jpg": {
    "width": 4032,
    "height": 2268,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Haus/gaestehaus-balkon-ausblick-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Haus/gaestehaus-balkon-ausblick-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Haus/gaestehaus-balkon-ausblick-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Haus/gaestehaus-balkon-ausblick-1600.webp"
      }
    ]
  },
  "/images/Haus/familie-hueber.jpg": {
    "width": 768,
    "height": 1024,
    "variants": [
      {
        "width": 480,
        "height": 640,
        "src": "/images/optimized/Haus/familie-hueber-480.webp"
      },
      {
        "width": 768,
        "height": 1024,
        "src": "/images/optimized/Haus/familie-hueber-768.webp"
      }
    ]
  },
  "/images/Haus/weissbriach-kirche.jpg": {
    "width": 2048,
    "height": 1152,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Haus/weissbriach-kirche-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Haus/weissbriach-kirche-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Haus/weissbriach-kirche-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Haus/weissbriach-kirche-1600.webp"
      }
    ]
  },
  "/images/Haus/gaestehaus-pavillon.jpg": {
    "width": 2048,
    "height": 1152,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Haus/gaestehaus-pavillon-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Haus/gaestehaus-pavillon-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Haus/gaestehaus-pavillon-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Haus/gaestehaus-pavillon-1600.webp"
      }
    ]
  },
  "/images/Haus/gaestehaus-winter-ansicht.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Haus/gaestehaus-winter-ansicht-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Haus/gaestehaus-winter-ansicht-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Haus/gaestehaus-winter-ansicht-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Haus/gaestehaus-winter-ansicht-1600.webp"
      }
    ]
  },
  "/images/Haus/gaestehaus-winter.png": {
    "width": 4032,
    "height": 2268,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Haus/gaestehaus-winter-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Haus/gaestehaus-winter-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Haus/gaestehaus-winter-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Haus/gaestehaus-winter-1600.webp"
      }
    ]
  },
  "/images/Umgebung/winter-balkon-ausblick-hero.jpg": {
    "width": 2048,
    "height": 1152,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Umgebung/winter-balkon-ausblick-hero-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Umgebung/winter-balkon-ausblick-hero-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Umgebung/winter-balkon-ausblick-hero-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Umgebung/winter-balkon-ausblick-hero-1600.webp"
      }
    ]
  },
  "/images/Umgebung/nassfeld-lift.jpg": {
    "width": 2048,
    "height": 1536,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/nassfeld-lift-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/nassfeld-lift-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/nassfeld-lift-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/nassfeld-lift-1600.webp"
      }
    ]
  },
  "/images/Umgebung/ski_nassfeld.jpg": {
    "width": 3024,
    "height": 4032,
    "variants": [
      {
        "width": 480,
        "height": 640,
        "src": "/images/optimized/Umgebung/ski_nassfeld-480.webp"
      },
      {
        "width": 768,
        "height": 1024,
        "src": "/images/optimized/Umgebung/ski_nassfeld-768.webp"
      },
      {
        "width": 1280,
        "height": 1707,
        "src": "/images/optimized/Umgebung/ski_nassfeld-1280.webp"
      },
      {
        "width": 1600,
        "height": 2133,
        "src": "/images/optimized/Umgebung/ski_nassfeld-1600.webp"
      }
    ]
  },
  "/images/Umgebung/freibad.png": {
    "width": 1024,
    "height": 1024,
    "variants": [
      {
        "width": 480,
        "height": 480,
        "src": "/images/optimized/Umgebung/freibad-480.webp"
      },
      {
        "width": 768,
        "height": 768,
        "src": "/images/optimized/Umgebung/freibad-768.webp"
      },
      {
        "width": 1024,
        "height": 1024,
        "src": "/images/optimized/Umgebung/freibad-1024.webp"
      }
    ]
  },
  "/images/Umgebung/sauna.png": {
    "width": 1024,
    "height": 1024,
    "variants": [
      {
        "width": 480,
        "height": 480,
        "src": "/images/optimized/Umgebung/sauna-480.webp"
      },
      {
        "width": 768,
        "height": 768,
        "src": "/images/optimized/Umgebung/sauna-768.webp"
      },
      {
        "width": 1024,
        "height": 1024,
        "src": "/images/optimized/Umgebung/sauna-1024.webp"
      }
    ]
  },
  "/images/Umgebung/aussicht-vom-golz.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/aussicht-vom-golz-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/aussicht-vom-golz-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/aussicht-vom-golz-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/aussicht-vom-golz-1600.webp"
      }
    ]
  },
  "/images/Umgebung/eis.JPG": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/eis-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/eis-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/eis-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/eis-1600.webp"
      }
    ]
  },
  "/images/Umgebung/garnitzenklamm.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/garnitzenklamm-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/garnitzenklamm-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/garnitzenklamm-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/garnitzenklamm-1600.webp"
      }
    ]
  },
  "/images/Umgebung/napal-alm.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/napal-alm-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/napal-alm-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/napal-alm-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/napal-alm-1600.webp"
      }
    ]
  },
  "/images/Umgebung/presseggersee.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/presseggersee-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/presseggersee-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/presseggersee-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/presseggersee-1600.webp"
      }
    ]
  },
  "/images/Umgebung/radfahren.jpg": {
    "width": 3024,
    "height": 4032,
    "variants": [
      {
        "width": 480,
        "height": 640,
        "src": "/images/optimized/Umgebung/radfahren-480.webp"
      },
      {
        "width": 768,
        "height": 1024,
        "src": "/images/optimized/Umgebung/radfahren-768.webp"
      },
      {
        "width": 1280,
        "height": 1707,
        "src": "/images/optimized/Umgebung/radfahren-1280.webp"
      },
      {
        "width": 1600,
        "height": 2133,
        "src": "/images/optimized/Umgebung/radfahren-1600.webp"
      }
    ]
  },
  "/images/Umgebung/schnee-wanderung.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/schnee-wanderung-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/schnee-wanderung-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/schnee-wanderung-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/schnee-wanderung-1600.webp"
      }
    ]
  },
  "/images/Umgebung/skigebiet-weissbriach-2.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/skigebiet-weissbriach-2-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/skigebiet-weissbriach-2-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/skigebiet-weissbriach-2-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/skigebiet-weissbriach-2-1600.webp"
      }
    ]
  },
  "/images/Umgebung/skigebiet-weissbriach.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/skigebiet-weissbriach-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/skigebiet-weissbriach-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/skigebiet-weissbriach-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/skigebiet-weissbriach-1600.webp"
      }
    ]
  },
  "/images/Umgebung/weissbriach.jpg": {
    "width": 2048,
    "height": 1536,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Umgebung/weissbriach-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Umgebung/weissbriach-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Umgebung/weissbriach-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Umgebung/weissbriach-1600.webp"
      }
    ]
  },
  "/images/Nr1/main.jpg": {
    "width": 1024,
    "height": 576,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Nr1/main-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Nr1/main-768.webp"
      },
      {
        "width": 1024,
        "height": 576,
        "src": "/images/optimized/Nr1/main-1024.webp"
      }
    ]
  },
  "/images/Nr1/living-room.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr1/living-room-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr1/living-room-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr1/living-room-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Nr1/living-room-1600.webp"
      }
    ]
  },
  "/images/Nr1/bedroom.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr1/bedroom-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr1/bedroom-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr1/bedroom-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Nr1/bedroom-1600.webp"
      }
    ]
  },
  "/images/Nr1/dining-room.jpg": {
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr1/dining-room-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr1/dining-room-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr1/dining-room-1280.webp"
      },
      {
        "width": 1600,
        "height": 1200,
        "src": "/images/optimized/Nr1/dining-room-1600.webp"
      }
    ]
  },
  "/images/Nr1/balcony.jpg": {
    "width": 1440,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr1/balcony-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr1/balcony-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr1/balcony-1280.webp"
      },
      {
        "width": 1440,
        "height": 1080,
        "src": "/images/optimized/Nr1/balcony-1440.webp"
      }
    ]
  },
  "/images/Nr1/balcony-seating.jpg": {
    "width": 1440,
    "height": 1080,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr1/balcony-seating-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr1/balcony-seating-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr1/balcony-seating-1280.webp"
      },
      {
        "width": 1440,
        "height": 1080,
        "src": "/images/optimized/Nr1/balcony-seating-1440.webp"
      }
    ]
  },
  "/images/Nr2/nr2-bedroom-double-bright.jpg": {
    "width": 1280,
    "height": 960,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr2/nr2-bedroom-double-bright-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr2/nr2-bedroom-double-bright-768.webp"
      },
      {
        "width": 1024,
        "height": 768,
        "src": "/images/optimized/Nr2/nr2-bedroom-double-bright-1024.webp"
      }
    ]
  },
  "/images/Nr2/nr2-living-room.jpg": {
    "width": 1280,
    "height": 960,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr2/nr2-living-room-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr2/nr2-living-room-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr2/nr2-living-room-1280.webp"
      }
    ]
  },
  "/images/Nr2/nr2-bedroom-overview-bright.jpg": {
    "width": 1280,
    "height": 960,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr2/nr2-bedroom-overview-bright-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr2/nr2-bedroom-overview-bright-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr2/nr2-bedroom-overview-bright-1280.webp"
      }
    ]
  },
  "/images/Nr2/nr2-kitchen-living.jpg": {
    "width": 1280,
    "height": 960,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr2/nr2-kitchen-living-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr2/nr2-kitchen-living-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr2/nr2-kitchen-living-1280.webp"
      }
    ]
  },
  "/images/Nr2/nr2-living-dining-bright.jpg": {
    "width": 1280,
    "height": 960,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr2/nr2-living-dining-bright-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr2/nr2-living-dining-bright-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr2/nr2-living-dining-bright-1280.webp"
      }
    ]
  },
  "/images/Nr2/nr2-balcony-seating.jpg": {
    "width": 1280,
    "height": 960,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr2/nr2-balcony-seating-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr2/nr2-balcony-seating-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr2/nr2-balcony-seating-1280.webp"
      }
    ]
  },
  "/images/Nr2/nr2-bathroom.jpg": {
    "width": 1280,
    "height": 960,
    "variants": [
      {
        "width": 480,
        "height": 360,
        "src": "/images/optimized/Nr2/nr2-bathroom-480.webp"
      },
      {
        "width": 768,
        "height": 576,
        "src": "/images/optimized/Nr2/nr2-bathroom-768.webp"
      },
      {
        "width": 1280,
        "height": 960,
        "src": "/images/optimized/Nr2/nr2-bathroom-1280.webp"
      }
    ]
  },
  "/images/Nr3/main.jpg": {
    "width": 1024,
    "height": 576,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Nr3/main-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Nr3/main-768.webp"
      },
      {
        "width": 1024,
        "height": 576,
        "src": "/images/optimized/Nr3/main-1024.webp"
      }
    ]
  },
  "/images/Nr3/sofa.jpeg": {
    "width": 4032,
    "height": 2268,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Nr3/sofa-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Nr3/sofa-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Nr3/sofa-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Nr3/sofa-1600.webp"
      }
    ]
  },
  "/images/Nr3/bed.jpeg": {
    "width": 4032,
    "height": 2268,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Nr3/bed-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Nr3/bed-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Nr3/bed-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Nr3/bed-1600.webp"
      }
    ]
  },
  "/images/Nr3/kitchen-tools.jpeg": {
    "width": 4032,
    "height": 2268,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Nr3/kitchen-tools-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Nr3/kitchen-tools-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Nr3/kitchen-tools-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Nr3/kitchen-tools-1600.webp"
      }
    ]
  },
  "/images/Nr3/view.jpeg": {
    "width": 4032,
    "height": 2268,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Nr3/view-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Nr3/view-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Nr3/view-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Nr3/view-1600.webp"
      }
    ]
  },
  "/images/Nr3/shoe-rack.jpeg": {
    "width": 4032,
    "height": 2268,
    "variants": [
      {
        "width": 480,
        "height": 270,
        "src": "/images/optimized/Nr3/shoe-rack-480.webp"
      },
      {
        "width": 768,
        "height": 432,
        "src": "/images/optimized/Nr3/shoe-rack-768.webp"
      },
      {
        "width": 1280,
        "height": 720,
        "src": "/images/optimized/Nr3/shoe-rack-1280.webp"
      },
      {
        "width": 1600,
        "height": 900,
        "src": "/images/optimized/Nr3/shoe-rack-1600.webp"
      }
    ]
  },
  "/images/Drohne/solar.png": {
    "width": 1184,
    "height": 864,
    "variants": [
      {
        "width": 480,
        "height": 350,
        "src": "/images/optimized/Drohne/solar-480.webp"
      },
      {
        "width": 768,
        "height": 560,
        "src": "/images/optimized/Drohne/solar-768.webp"
      },
      {
        "width": 1184,
        "height": 864,
        "src": "/images/optimized/Drohne/solar-1184.webp"
      }
    ]
  },
  "/images/Logo/logo-rader-gitschtal.jpg": {
    "width": 312,
    "height": 154,
    "variants": [
      {
        "width": 128,
        "height": 63,
        "src": "/images/optimized/Logo/logo-rader-gitschtal-128.webp"
      },
      {
        "width": 256,
        "height": 126,
        "src": "/images/optimized/Logo/logo-rader-gitschtal-256.webp"
      },
      {
        "width": 312,
        "height": 154,
        "src": "/images/optimized/Logo/logo-rader-gitschtal-312.webp"
      }
    ]
  },
  "/images/Logo/nassfeld-logo.png": {
    "width": 189,
    "height": 73,
    "variants": [
      {
        "width": 96,
        "height": 37,
        "src": "/images/optimized/Logo/nassfeld-logo-96.webp"
      },
      {
        "width": 189,
        "height": 73,
        "src": "/images/optimized/Logo/nassfeld-logo-189.webp"
      }
    ]
  },
  "/images/Logo/kaernten-logo.png": {
    "width": 277,
    "height": 200,
    "variants": [
      {
        "width": 96,
        "height": 69,
        "src": "/images/optimized/Logo/kaernten-logo-96.webp"
      },
      {
        "width": 192,
        "height": 139,
        "src": "/images/optimized/Logo/kaernten-logo-192.webp"
      },
      {
        "width": 277,
        "height": 200,
        "src": "/images/optimized/Logo/kaernten-logo-277.webp"
      }
    ]
  }
} as const satisfies Record<string, ResponsiveImage>;

export function getResponsiveImage(path: string) {
  return responsiveImages[path as keyof typeof responsiveImages] ?? null;
}

export function getImgSrc(path: string) {
  const image = getResponsiveImage(path);
  return image?.variants[0]?.src ?? path;
}

export function getImgSrcSet(path: string) {
  const image = getResponsiveImage(path);
  return image ? image.variants.map((variant) => `${variant.src} ${variant.width}w`).join(', ') : undefined;
}

export function getLargestImgSrc(path: string) {
  const image = getResponsiveImage(path);
  return image?.variants[image.variants.length - 1]?.src ?? path;
}
